###############################################################################
# synth_hm_300mhz.tcl
# Synopsys Design Compiler — INDIA_CRYPTO_SOC @ 300 MHz  (Hard-Macro Flow)
#
# Run from syn/hard_macro/scripts/:
#   dc_shell -f synth_hm_300mhz.tcl | tee synth_hm_300mhz.log
#
# Hard macros used in this flow
#   SRAM  : ARM Artisan TS1N28HPCPSVTB16384X32M8SW  (16384 × 32-bit, SVT)
#   PULP  : apb_uart / apb_spi_master / apb_i2c     (blackbox, .db required)
#
# Differences from the soft-macro flow (syn/scripts/synth_300mhz.tcl)
#   • +define+HARD_MACRO passed to every analyze command so sram_sp_wrap
#     instantiates the real macro rather than the behavioral register array
#   • SRAM .db added to link_library so DC can resolve the macro and run STA
#   • set_dont_touch applied to u_sram_macro so DC does not try to optimise
#     the hard macro boundary
#   • set_size_only on the sram_ctrl wrapper (DC may retime it; disallow)
###############################################################################

# ── 0. Paths ──────────────────────────────────────────────────────────────────
set DESIGN      india_crypto_soc
set SDC         ../constraints/india_crypto_soc_hm.sdc
set RTL_DIR     ../../../rtl
set OUT_DIR     ../outputs

file mkdir $OUT_DIR

# ── 1. PDK + Hard-Macro Library Setup ────────────────────────────────────────
#
# TSMC 28nm HPC+ standard-cell library (typical corner for compile).
# Adjust the path to match your PDK installation.
#
set PDK_LIB_DIR /pdk/tsmc28nm/tcbn28hpcplusbwp30p140_190a/TSMCHOME/digital/Front_End/timing_power_noise/NLDM/tcbn28hpcplusbwp30p140_180a
set SC_DB       ${PDK_LIB_DIR}/tcbn28hpcplusbwp30p140tt0p9v25c.db

# ARM Artisan SRAM .db — typical corner (TT / 0.9V / 25°C)
# The .db is generated by the memory compiler; adjust path accordingly.
set SRAM_DB     ../pdk/TS1N28HPCPSVTB16384X32M8SW_tt0p9v25c.db

# PULP IP timing models (provide .db files in pdk/ — see pdk/README.txt)
# Uncomment and set paths once you have them:
# set PULP_UART_DB  ../pdk/apb_uart_tt0p9v25c.db
# set PULP_SPI_DB   ../pdk/apb_spi_master_tt0p9v25c.db
# set PULP_I2C_DB   ../pdk/apb_i2c_tt0p9v25c.db

set target_library [list $SC_DB]
set link_library   [concat * $SC_DB $SRAM_DB]
# If PULP .db files are available, add them:
# set link_library [concat * $SC_DB $SRAM_DB $PULP_UART_DB $PULP_SPI_DB $PULP_I2C_DB]

# ── 2. Read All RTL (with HARD_MACRO define) ──────────────────────────────────
#
# +define+HARD_MACRO tells sram_sp_wrap to instantiate TS1N28HPCPSVTB16384X32M8SW
# instead of the behavioral register model.
#
# All files use -format sverilog because the RTL uses SystemVerilog constructs
# (logic, always_ff, always_comb, inline variable declarations).

# PULP vendor IP blackbox stubs — read first so wrappers can reference them
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/periph/vendor/pulp_blackbox.v

# Peripheral wrappers (AXI-Lite to APB bridges)
analyze -format sverilog +define+HARD_MACRO \
    [glob $RTL_DIR/periph/*.sv]

# CPU core and AES ISA extension
analyze -format sverilog +define+HARD_MACRO \
    [glob $RTL_DIR/core/*.v]

# SRAM hard-macro wrapper and arbiter/controller
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/mem/sram_sp_wrap.v
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/mem/sram_ctrl.v

# Crypto blocks
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/crypto/aes_ca_accel.v
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/crypto/india_pdf_engine.v
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/crypto/rosc_trng.v

# Fabric
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/fabric/axi_lite_xbar.v

# Top-level SoC
analyze -format sverilog +define+HARD_MACRO \
    $RTL_DIR/top/india_crypto_soc.v

elaborate $DESIGN

# ── 3. Link and Check ─────────────────────────────────────────────────────────
current_design $DESIGN
link
check_design > $OUT_DIR/check_design.rpt

# ── 4. Hard-Macro Boundary — Dont-Touch ───────────────────────────────────────
#
# Prevent DC from looking inside the hard macro or moving logic across
# its boundary.  sram_ctrl is the RTL wrapper; we allow DC to optimise it
# but not to retime through the macro registers.
#
set_dont_touch [get_cells -hierarchical u_sram_macro]

# Prevent retiming across the SRAM registered output boundary
set_dont_touch [get_cells u_sram_ctrl/u_sram]

# ── 5. Apply Constraints ──────────────────────────────────────────────────────
source $SDC

# ── 6. Compile Phase 1 — Ungrouped, area-optimised baseline ──────────────────
compile_ultra \
    -no_autoungroup \
    -retime

# ── 7. Compile Phase 2 — Incremental timing-driven ───────────────────────────
compile_ultra \
    -incremental \
    -retime \
    -timing_high_effort_script

# ── 8. Reports ────────────────────────────────────────────────────────────────
report_timing -delay max \
              -path_type full_clock_expanded \
              -nworst 10 \
              -significant_digits 3 \
              > $OUT_DIR/timing_setup.rpt

report_timing -delay min \
              -nworst 5 \
              > $OUT_DIR/timing_hold.rpt

report_area   -hierarchy > $OUT_DIR/area.rpt
report_power  -hierarchy > $OUT_DIR/power.rpt
report_qor                > $OUT_DIR/qor.rpt

# ── 9. Verify WNS / TNS ───────────────────────────────────────────────────────
set wns [get_attribute [get_timing_paths -delay max] slack]
if {$wns < 0} {
    puts "ERROR: Timing FAILED. WNS = ${wns} ns. Check timing_setup.rpt."
} else {
    puts "INFO: Timing PASSED. WNS = ${wns} ns at 300 MHz (hard-macro flow)."
}

# ── 10. Write Outputs ─────────────────────────────────────────────────────────
write -format verilog  -hierarchy -output $OUT_DIR/${DESIGN}_hm_netlist.v
write -format ddc                 -output $OUT_DIR/${DESIGN}_hm.ddc
write_sdc                                 $OUT_DIR/${DESIGN}_hm_final.sdc
write_sdf -version 3.0                    $OUT_DIR/${DESIGN}_hm.sdf

puts "Hard-macro synthesis complete. Outputs in $OUT_DIR/"
